livery = {

	{"f18c1", 0 ,"f18c_1_dif",false}; -- GŁOWNA CZĘŚĆ SKŁADOWA --
	{"f18c1", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};

	
	{"f18c2", 0 ,"f18c_2_dif",false}; -- GŁOWNA CZĘŚĆ SKŁADOWA --
	{"f18c2", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};

	
	{"FPU_8A", 0 ,"FPU_8A",false}; --  ZBIORNIK PALIWA
	{"FPU_8A", 2 ,"FPU_8A_Diff_RoughMet",true};
	
	-- NOS GÓRA CYFRY POCZĄTEK -- 
	-- LEWA STRONA --
	{"F18C_BORT_NUMBER_NOSE_L_100", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_L_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_L_100", DECAL ,"NumeryL_NOS",false}; 
	
	{"F18C_BORT_NUMBER_NOSE_L_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_L_10", DECAL ,"NumeryL_NOS",false}; 

	{"F18C_BORT_NUMBER_NOSE_L_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_L_01", DECAL ,"NumeryL_NOS",false}; 
	
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_NOSE_R_100", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_R_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_R_100", DECAL ,"NumeryR_NOS",false}; 
	
	{"F18C_BORT_NUMBER_NOSE_R_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_R_10", DECAL ,"NumeryR_NOS",false}; 	

	{"F18C_BORT_NUMBER_NOSE_R_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_R_01", DECAL ,"NumeryR_NOS",false}; 
	--NOS GÓRA CYFRY KONIEC--
	
	
	

	-- FLAPY CYFRY POCZĄTEK--
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_ZAK_L_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_ZAK_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_L_100", DECAL ,"NumeryFLAPY",false};  
	
	{"F18C_BORT_NUMBER_ZAK_L_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_ZAK_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_L_10", DECAL ,"NumeryFLAPY",false}; 	

	{"F18C_BORT_NUMBER_ZAK_L_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_ZAK_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_L_01", DECAL ,"NumeryFLAPY",false}; 
	
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_ZAK_R_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_ZAK_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_R_100", DECAL ,"NumeryFLAPY",false}; 
	
	{"F18C_BORT_NUMBER_ZAK_R_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_ZAK_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_R_10", DECAL ,"NumeryFLAPY",false}; 	

	{"F18C_BORT_NUMBER_ZAK_R_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_ZAK_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_R_01", DECAL ,"NumeryFLAPY",false}; 
	--FLAPY CYFRY KONIEC--
	
	--STATECZNIK PIONOWY GÓRNE CYFRY POCZĄTEK--
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_KIL_L_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_L_100", DECAL ,"NumerySTER",false}; 
	
	{"F18C_BORT_NUMBER_KIL_L_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_L_10", DECAL ,"NumerySTER",false}; 	

	{"F18C_BORT_NUMBER_KIL_L_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_L_01", DECAL ,"NumerySTER",false}; 	
	
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_KIL_R_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_R_100", DECAL ,"NumerySTER",false}; 
	
	{"F18C_BORT_NUMBER_KIL_R_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_R_10", DECAL ,"NumerySTER",false}; 	

	{"F18C_BORT_NUMBER_KIL_R_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_R_01", DECAL ,"NumerySTER",false}; 
	--STATECZNIK PIONOWY GÓRNE CYFRY KONIEC--	

	
	
	-- NOS DÓŁ MNIEJSZE CYFRY POCZĄTEK -- 
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_NOSE_kuw_L_100", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_100", DECAL ,"empty",true}; 
	
	{"F18C_BORT_NUMBER_NOSE_kuw_L_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_10", DECAL ,"empty",true}; 

	{"F18C_BORT_NUMBER_NOSE_kuw_L_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_01", DECAL ,"empty",true}; 
	

	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_NOSE_kuw_R_100", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_100", DECAL ,"empty",true}; 
	
	{"F18C_BORT_NUMBER_NOSE_kuw_R_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_10", DECAL ,"empty",true}; 

	{"F18C_BORT_NUMBER_NOSE_kuw_R_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_01", DECAL ,"empty",true}; 	
	-- NOS DÓŁ MNIEJSZE CYFRY KONIEC --

	-- STATECZNIK PIONOWY ŚRODKOWE NAJWIĘKSZE CYFRY POCZĄTEK -- 
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_KIL_Kuw_R_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_100", DECAL ,"empty",true}; 
	
	{"F18C_BORT_NUMBER_KIL_Kuw_R_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_KIL_Kuw_R_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_01", DECAL ,"empty",true}; 	
	
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_KIL_Kuw_L_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_100", DECAL ,"empty",true}; 
	
	{"F18C_BORT_NUMBER_KIL_Kuw_L_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_KIL_Kuw_L_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_01", DECAL ,"empty",true}; 	
	-- STATECZNIK PIONOWY ŚRODKOWE NAJWIĘKSZE CYFRY KONIEC -- 


	-- NOS DÓŁ POD OWIEWKĄ ALE NISKO CYFRY POCZĄTEK --  
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_NOSE_fin_L_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_fin_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_L_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_NOSE_fin_L_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_fin_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_L_01", DECAL ,"empty",true}; 
	
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_NOSE_fin_R_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_fin_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_R_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_NOSE_fin_R_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_NOSE_fin_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_R_01", DECAL ,"empty",true}; 	
	-- NOS DÓŁ POD OWIEWKĄ ALE NISKO CYFRY KONIEC --  	
	
	

	-- STATECZNIK PIONOWY NAJNIŻSZE CYFRY POCZĄTEK -- 
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_KIL_Switz_R_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Switz_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_R_100", DECAL ,"empty",true}; 	
	
	{"F18C_BORT_NUMBER_KIL_Switz_R_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Switz_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_R_10", DECAL ,"empty",true}; 		

	{"F18C_BORT_NUMBER_KIL_Switz_R_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Switz_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_R_01", DECAL ,"empty",true}; 	
	
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_KIL_Switz_L_100", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Switz_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_L_100", DECAL ,"empty",true}; 	  
	
	{"F18C_BORT_NUMBER_KIL_Switz_L_10", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Switz_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_L_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_KIL_Switz_L_01", 0 ,"f18c_2_dif",false};
	{"F18C_BORT_NUMBER_KIL_Switz_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_L_01", DECAL ,"empty",true}; 	 
	-- STATECZNIK PIONOWY NAJNIŻSZE CYFRY KONIEC -- 
	
	
	
	-- NOS DÓŁ PRAKTYCZNIE POD SPODEM CYFRY POCZĄTEK --  
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_STV_aus_R_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_STV_aus_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_R_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_STV_aus_R_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_STV_aus_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_R_01", DECAL ,"empty",true}; 	
	
	--LEWA STRONA--
	{"F18C_BORT_NUMBER_STV_aus_L_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_STV_aus_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_L_10", DECAL ,"empty",true}; 	

	{"F18C_BORT_NUMBER_STV_aus_L_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_STV_aus_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_L_01", DECAL ,"empty",true}; 	
	-- NOS DÓŁ PRAKTYCZNIE POD SPODEM CYFRY KONIEC -- 

	-- ZA SKRZYDŁEM TAM GDZIE NAPIS NAVY CYFRY POCZĄTEK--
	--PRAWA STRONA--
	{"F18C_BORT_NUMBER_MTW_aus_R_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_MTW_aus_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_MTW_aus_R_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_MTW_aus_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_R_01", DECAL ,"empty",true};	

	--LEWA STRONA--
	{"F18C_BORT_NUMBER_MTW_aus_L_10", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_MTW_aus_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_MTW_aus_L_01", 0 ,"f18c_1_dif",false};
	{"F18C_BORT_NUMBER_MTW_aus_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_L_01", DECAL ,"empty",true};	
	-- ZA SKRZYDŁEM TAM GDZIE NAPIS NAVY CYFRY KONIEC--


	{"pilot_F18", 0 ,"../VFA-203 Line/pilot_F18_tan",false}; -- MUNDUR PILOTA I TWARZ
	{"pilot_F18_helmet", 0 ,"../VFA-203 Line/pilot_F18_helmet_white",false}; -- HEŁM PILOTA
	{"pilot_F18_patch", 0 ,"../VFA-203 Line/pilot_F18_patch",false}; -- NALEPKA NA RAMIE Z LOGO SQUADRONU

--[[
PUSTE ", DECAL ,"empty",true};"
Z NUMEREM ", DECAL ,"F18C_numery",true};	"
]]
	
}
name = "VFA-203 Aggressor 2" -- NAZWA WYŚWIETLANA W DCS